require "level.utils"
require "variables"
function init(self)
    self.speed = 900
end

function update(self, dt)
    local pos = go.get_position()
    if pos.x < -1000 or reset then
        go.delete(true)
    end
    pos.x = pos.x - self.speed * dt
    go.set_position(pos)
    msg.post(current_level..":/controller#script", "speed_request")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("set_speed") then
        self.speed = message.speed 
    end
end