components {
  id: "script"
  component: "/bosses/boss_1/gluttony.script"
}
embedded_components {
  id: "running_state"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"hero\"\n"
  "mask: \"geometry\"\n"
  "mask: \"danger\"\n"
  "mask: \"impact\"\n"
  "mask: \"impact_soft\"\n"
  "mask: \"obstacle\"\n"
  "mask: \"coin\"\n"
  "mask: \"coin2\"\n"
  "mask: \"coin3\"\n"
  "mask: \"pole\"\n"
  "mask: \"impact\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 50.0\n"
  "  data: 85.0\n"
  "  data: 9.6\n"
  "}\n"
  ""
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"player_run_black\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/hero/sirod.atlas\"\n"
  "}\n"
  ""
  position {
    x: 3.0
    z: 1.0
  }
}
embedded_components {
  id: "sliding_state"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"hero\"\n"
  "mask: \"geometry\"\n"
  "mask: \"danger\"\n"
  "mask: \"still_slide\"\n"
  "mask: \"impact\"\n"
  "mask: \"impact_soft\"\n"
  "mask: \"obstacle\"\n"
  "mask: \"coin\"\n"
  "mask: \"coin2\"\n"
  "mask: \"coin3\"\n"
  "mask: \"impact\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: -42.5\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 50.0\n"
  "  data: 42.5\n"
  "  data: 7.4\n"
  "}\n"
  ""
}
embedded_components {
  id: "rolling_over_state"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"hero\"\n"
  "mask: \"geometry\"\n"
  "mask: \"danger\"\n"
  "mask: \"still_roll\"\n"
  "mask: \"obstacle\"\n"
  "mask: \"rolling_platform\"\n"
  "mask: \"coin\"\n"
  "mask: \"coin2\"\n"
  "mask: \"coin3\"\n"
  "mask: \"impact\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: 42.5\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 50.0\n"
  "  data: 42.5\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "jumping_state"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"hero\"\n"
  "mask: \"geometry\"\n"
  "mask: \"danger\"\n"
  "mask: \"still_roll\"\n"
  "mask: \"obstacle\"\n"
  "mask: \"rolling_platform\"\n"
  "mask: \"coin\"\n"
  "mask: \"coin2\"\n"
  "mask: \"coin3\"\n"
  "mask: \"pole\"\n"
  "mask: \"impact\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: 22.5\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 50.0\n"
  "  data: 62.5\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "dead_state"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 0.5\n"
  "  data: 0.5\n"
  "  data: 10.0\n"
  "}\n"
  ""
}
