--ground.script
local pieces = {"go", "go1", "go2", "go3", "go4", "go5", "go6"}
function init(self)
	self.speed = 360
end

function update(self, dt)
	for i, p in ipairs(pieces) do
		local pos = go.get_position(p)
		if pos.x <= -1090 then
			pos.x = 1368 + (pos.x + 228)
		end
		pos.x = pos.x - self.speed * dt
		go.set_position(pos, p)
	end
end

function on_message(self, message_id, message, sender)
    if message_id == hash("set_speed") then 
        self.speed = message.speed 
    end
end