--ground.script
function init(self)
	self.speed = 360
end

function update(self, dt)
	msg.post("level:/controller#script", "speed_request")
	local pos = go.get_position(p)
	if pos.x <= -990 then
		pos.x = 2970 + (pos.x + 330)
	end
	pos.x = pos.x - self.speed * dt
	go.set_position(pos, p)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("set_speed") then 
		self.speed = message.speed 
	end
end